### ISSUE TITLE
Right switch [hold top] card never fires

### ISSUE THREAD

**Issue by goyaweb** [caseda/com.tkbhome#1]
Same for Right switch [hold bottom] card. I assume this card would fire if you would press the right switch (also tried holding it for multiple seconds but didn't work either)

**Comment by caseda** [comment]
the hold bottom is going to be removed in the next update, it didn't work, but also, it will never work, it couldn't even have worked at all 😄

There will be (only) 4 flow cards in the next update for the right switch:
Single press on
Single press off
Double press on
Double press off

**Comment by goyaweb** [comment]
why could it never work? it works in Vera

**Comment by caseda** [comment]
Since the device only send basic_set commands for both the left and the right switches

I am surprised that they even made it work with the right switch at all, since it needed a really custom code to even get that realized.

**Comment by caseda** [comment]
the device does not send any other commands then i already know of (and the driver is written for), so no hold for the buttons,
Checked it now with an original sigma tool.

So if vera managed to do it, then they made real magic happen,

so i will close this issue now since it will never happen
