### ISSUE TITLE
TKB_TZ67-G not pairing as tbk

### ISSUE THREAD

**Issue by posthok** [caseda/com.tkbhome#10]
Just bought a tbk TZ67-G wall plug dimmer as a replacement for a broken everspring dimmer.
When pairing, Homey said it only can paired as a generic device???
Paired as a generic device it's not dimmable

**Comment by caseda** [comment]
what version of the app are you using?
and which version of the TZ67, the normal or z-wave plus version

**Comment by posthok** [comment]
Homey 1.1.2 en TKB app V1.0. Dimmer TKB_TZ67-G

**Comment by posthok** [comment]
![zones devices homey](https://cloud.githubusercontent.com/assets/6661318/21611985/7e2ebf6e-d1cf-11e6-9760-aa9146123661.png)

**Comment by caseda** [comment]
oh right, that version is not in the app store yet, will be included in the next update, or you can of course install this latest github version that has the support already added

**Comment by posthok** [comment]
Ok Thanx, Will do that

**Comment by posthok** [comment]
installing github version popsup an error : Invalid JSON in app.json [SyntaxError: Unexpected token }]

**Comment by posthok** [comment]
Installed the branch with the test driver also V1.01 but still sees the dimmer as a generic device

**Comment by caseda** [comment]
test driver is an entirely other device :wink: but my bad i made a mistake in the git version 1.0.1, fixed now

**Comment by posthok** [comment]
Thanks again!!

**Comment by posthok** [comment]
Great!! it's working now.
