### ISSUE TITLE
New/Other ID's for the TZ67 wall plug dimmer

### ISSUE THREAD

**Issue by aelsenaar** [caseda/com.tkbhome#12]
Ordered a new TBK Home wall plug dimmer but is was not  recognized by the app. It seems this TZ67 dimmer is using the following ID's:
- Fab ID: 280
- Product Type ID: 3
- Product ID: 8

As a test I copied the TZ67 driver with the new ID's and everything seems to work fine. Can you update the app? Thx in advance.
![screenshot_20170104_153533](https://cloud.githubusercontent.com/assets/16883460/21645828/ed683882-d293-11e6-9916-c8b915eb6f11.png)

Alexander

**Comment by caseda** [comment]
You are only the thirth person wanting it included, and like the other times, it is already implemented in the upcoming update that is already on github, only busy with final adjustments to another driver before putting it on the app store

it is not just another id though, the chip inside has been updated completely :wink:

**Comment by aelsenaar** [comment]
Sorry, was not aware this was the -plus version of the wall plug. Will check github better next time.

**Comment by caseda** [comment]
Has been included in the app for some time now. Closing it.
