### ISSUE TITLE
Hw switch

### ISSUE THREAD

**Issue by djeskoswe** [caseda/com.tkbhome#14]
HW switch updates has stopped working,  FW update?  

Let me know what to test etc..

**Comment by caseda** [comment]
what have you all tried to "fix" the issue,
as there has been nothing changed in those parts of the code where the device talks with/in

have you changed any settings?
is the Manual State Interval still on a value?
if there still as a value other then 0 try changing it, save
and then back to what you had it before (Range 60 - 3600),
and save the settings

**Comment by djeskoswe** [comment]
Will try more tomorrow,  thanks

**Comment by djeskoswe** [comment]
Works...
