### ISSUE TITLE
Please add support for TZ88

### ISSUE THREAD

**Issue by sjaakie33** [caseda/com.tkbhome#20]
Good day,

please add support for TZ88 wall plug

http://products.z-wavealliance.org/products/1324
[TKB TZ88 manual-20150527 (1) (1).pdf](https://github.com/caseda/com.tkbhome/files/902084/TKB.TZ88.manual-20150527.1.1.pdf)
manufacture id 280
product type id 1
product id 1

With kind regards,

René Ardley

**Comment by caseda** [comment]
Can you confirm the id 's?
Tkb Id's are not always right on the Alliance's website. 

You can see the id's in the device's settings after you include it as an unknown device

**Comment by sjaakie33** [comment]
Yes I can confirm I'd are the ones of homey

With kind regards,

René Ardley


Op 6 apr. 2017 12:06 schreef R Mengers <notifications@github.com>:

Can you confirm the id 's?
Tkb Id's are not always right on the Alliance's website.

You can see the id's in the device's settings after you include it as an unknown device

**Comment by caseda** [comment]
it is added (and should be working) in the next update (v1.0.6)

it is awaiting approval by athom in the appstore as we speak.

**Comment by sjaakie33** [comment]
OK thanks
Good work


Op 30 apr. 2017 20:23 schreef R Mengers <notifications@github.com>:

it is added (and should be working) in the next update (v1.0.6)

it is awaiting approval by athom in the appstore as we speak.

**Comment by sjaakie33** [comment]
good day,

today try to add tz88
it's going good until i have to select type of connector connected.
then i get a error message with invalid capacity.

with kinds regards 

René

**Comment by caseda** [comment]
what homey version are you on?

and what of type did you select, since its an odd error.

**Comment by sjaakie33** [comment]
version homey 1.2.2


________________________________
Van: R Mengers <notifications@github.com>
Verzonden: woensdag 3 mei 2017 00:39
Aan: caseda/com.tkbhome
CC: sjaakie33; Author
Onderwerp: Re: [caseda/com.tkbhome] Please add support for TZ88 (#20)


what homey version are you on?

**Comment by caseda** [comment]
Found the issue, accidentally used the wrong capability name (measure_amperage vs measure_current) will send the fix in now to be accepted into the appstore

sorry for the inconvenience! time for a new pair of glasses i think

**Comment by sjaakie33** [comment]
Thanks it works good
