### ISSUE TITLE
tz88 configuration page: auto off timer

### ISSUE THREAD

**Issue by sjaakie33** [caseda/com.tkbhome#22]
tz88 configuration page: auto off timer to be off =0 but minimum number =1 to accepted to save

**Comment by caseda** [comment]
oops, you are correct, limited to 1 now, will fix it in the app when including the tz37 also, which is pretty much done, i think tomorrow morning,
and then the app needs to be accepted of course, that is variable, sometime an hour (when very lucky), sometimes it takes a few days.

**Comment by caseda** [comment]
fixed in 1.0.8 which is now in the app store
