### ISSUE TITLE
Support for TKB TZ69E Wall Plug Switch/Meter?

### ISSUE THREAD

**Issue by lesterchan** [caseda/com.tkbhome#23]
Bought The TKB TZ69E Wall Plug Switch/Meter from Vesternet http://www.vesternet.com/z-wave-tkb-tz69e-wall-plug-switch-meter-gen5-uk and realized it is not supported.

Here are the details:
```
Manufacturer ID: 280
Product Type ID: 785
Product ID: 259
```

**Comment by caseda** [comment]
ID's are added into the app, and the update is awaiting approval by athom
