### ISSUE TITLE
TSM02 No_Mobile

### ISSUE THREAD

**Issue by johnniemalm** [caseda/com.tkbhome#24]
I get No_Mobile on the 2 pcs of this that I have, try to enable/disable, uninstall and instal again, but no luck

**Comment by caseda** [comment]
No_mobile?
Could you post a screenshot of that?
Cause I'm not sure what is meant here, never heard of such an error.

**Comment by johnniemalm** [comment]
![skarmavbild 2017-10-15 kl 18 18 55](https://user-images.githubusercontent.com/17321613/31586748-75594788-b1d5-11e7-8595-0b1f19b18fb3.png)

**Comment by johnniemalm** [comment]
this is when I press to the left of settings , don't know what it´s called

**Comment by caseda** [comment]
hmm, could you try to open the so called mobile card (that's really what it is called) in a normal browser? best option is chrome.

**Comment by johnniemalm** [comment]
![skarmavbild 2017-10-15 kl 19 13 45](https://user-images.githubusercontent.com/17321613/31587174-0f797da4-b1dd-11e7-819b-217913bb6ff4.png)

**Comment by caseda** [comment]
and you can open the mobile card with other devices?

**Comment by johnniemalm** [comment]
Yes, only this 2 devices

**Comment by johnniemalm** [comment]
![skarmavbild 2017-10-16 kl 06 47 53](https://user-images.githubusercontent.com/17321613/31595728-ffc111c2-b23d-11e7-82e6-07e5e6d8a3cd.png)

**Comment by caseda** [comment]
I found the issue, will fix it when I get home this evening.

Sorry for the inconvenience :smile:

**Comment by johnniemalm** [comment]
No problem, Thanks

**Comment by caseda** [comment]
The fix is awaiting for approval by athom

**Comment by johnniemalm** [comment]
Working perfect now , Thanks
