### ISSUE TITLE
TZ35/TZ55

### ISSUE THREAD

**Issue by juw2** [caseda/com.tkbhome#29]
Hi.
I found an issue in the code for driver TZ35.
The flowcards for button 2 is not working and thats because a new "section" in app.json needs to be added for TZ35D_... and also the driver.js needs to be changed to match the flow.
Now it is configured against TZ65D_...
I have tried to do the changes and they work fine but it would be nice to get it fixed in the official release.

**Comment by caseda** [comment]
Ah right, must have forgotten that when I was splitting the drivers up.

Thank you for reporting.
