### ISSUE TITLE
Something went wrong addressing device (Transmit_Complete_Ack_Unknown)

### ISSUE THREAD

**Issue by vaderag** [caseda/com.tkbhome#34]
I have recently seen an issue with my TKB Plug
I get the error in the title when trying to switch via Homey

I can remove and re-pair it successfully, it will work for a short period, but every time same issue occurs. 

Per thread here: https://forum.athom.com/discussion/comment/71038/#Comment_71038

Thanks

**Comment by caseda** [comment]
This is not an app issue (the app does not do any of the communication things),

but either a
- range issue (common for "ack-unknown" devices);
- A (the) relaying device not working properly;
- Or one of the homey core issues.

So please try these things:

- confirm it is not a range issue (place homey nearby to see if it then works),
- Heal any devices nearby that could be relaying the signal (from the developer tools)
- Or if that is not fixing it, please make this an issue in the normal homey issues.

As this is not an app issue I will close it here.
