### ISSUE TITLE
Schakelaar TZ04 toevoegen

### ISSUE THREAD

**Issue by FredSanPedro** [caseda/com.tkbhome#36]
Beste Michel,

Ik heb de schakelaar TZ04 van TBKHOME gekocht en de bijbehorende app geïnstalleerd op Homey. Echter de bijbehorende switch is niet aanwezig. Hij installeert hem alleen als basis z-wave switch maar dan is hij nagenoeg onbruikbaar. Kunnen jullie s.v.p. de juiste switch toevoegen?
Alvast bedankt.

https://products.z-wavealliance.org/products/823

Met vriendelijke groeten, Fred Pols

**Comment by caseda** [comment]
Hallo,

Zou je de product (type) id's kunnen verifiëren? (liefst een screenshot van de node information)
De id's op de zwave Alliance website kloppen vaak niet met de werkelijkheid als het om tkb gaat.

**Comment by caseda** [comment]
Please give me the information i was asking for, otherwise i can not include it into the app.

Geef alstublieft de informatie waar ik om vroeg, zonder deze informatie kan ik het apparaat niet aan de app toevoegen.

**Comment by FredSanPedro** [comment]
Ja dat kan ik doen maar dat moet op de behuizing van de switch staan toch? Het apparaat zit ingebouwd in mijn huis in Spanje en ik ben pas 26 september weer in Spanje dus daarna zal ik het doen.

**Comment by caseda** [comment]
Als je de homey kan bereiken (en hij is daar nog geincludeerd) dan kan je het in de apparaat zijn settings zien (het kleine steeksleuteltje) onder "node informatie".

Ik denk niet dat het zo op de module staat gedrukt.

**Comment by FredSanPedro** [comment]
Is dit wat je bedoelt?

**Comment by kolobus** [comment]
Hello.

Here is information for TZ04 dual channel relay:

<img width="467" alt="homey" src="https://user-images.githubusercontent.com/2559459/49104837-18cb7700-f290-11e8-8ceb-1733e37eed02.png">

I can also upload scanned manual if it's needed.

Would be awesome to have those relays added. Thank you!

**Comment by kolobus** [comment]
It seems TZ04 already added with correct id's, just 2.0.2 version not published in Homey apps. Sorry for that. Waiting for version update then.

**Comment by caseda** [comment]
Added as of 2.0.2, if it still isn't recognized properly, feel free to re-open
