### ISSUE TITLE
TKB Home TZ55-S not recognized

### ISSUE THREAD

**Issue by Peerlkamp** [caseda/com.tkbhome#37]
When I want to add the TKB Home 55-S single dimmer to Homey I get the following message 'No suitable homey app was found for this device'. Now I can not dim my light. only on off, because homey uses an default z-wave device.

Am I doing something wrong?

**Comment by caseda** [comment]
You probably have a newer version then is in the app right now, so the device's id's are not in the app.

Can you specify which id's you have?
You can find them in de node information of the device's settings.

**Comment by Peerlkamp** [comment]
Dear Caseda,

Hereby i send you the ID of my TZ55-S.

![tkbhome](https://user-images.githubusercontent.com/30841502/42154834-528a382a-7dd6-11e8-8d6c-df342cb27694.jpg)

**Comment by caseda** [comment]
thank you, will be added into the next update

**Comment by Peerlkamp** [comment]
That is amazing. When will the next update be released?

**Comment by caseda** [comment]
Depends a littlebit on another user that also wants to have his/her device included.

**Comment by caseda** [comment]
Added as of 2.0.2, if it doesn't get recognized still, feel free to re-open
