### ISSUE TITLE
TSP01/TSM02 Continual crashes

### ISSUE THREAD

**Issue by citizenxnz** [caseda/com.tkbhome#39]
Hi

The app keeps crashing on motion and contact.  The log is:

MaxListenersExceeded-Warning:  Possible EventEmitter memory leak detected: 11 __appInit listeners added.  Use emitter.setMaxListeners() to increase limit
<date>[Err] [ManagerDrivers] [TSP01] [0] do not use getOnStart for battery devices, use getOnOnline instead
[node:8870] UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid card id
[node:8870] [DEP0018] DepreciationWarning: Unhandled promise rejections are deprecated.  In the future, promise rejections that are not handled will terminate the Node.js proces with a non-zero exit code
/drivers/TSP01/device.js:37

**Comment by damianxd** [comment]
It's the same for me, it happens whenever I add any of the multi sensor

**Comment by caseda** [comment]
I will add this fix somewhere this week into the app, having a little bit of difficulty with the "new" CLI of athom where the app currently not is validating correctly (even though the reason it fails on, it should just validate correctly), so need to work around that one.
(also my spare time is a little bit restricted currently, so hopefully soon)

**Comment by damianxd** [comment]
Thanks for your work @caseda, I really appreciate it.

**Comment by caseda** [comment]
the fix is in the wait, but until i can validate the app i can't update te app in the store (https://github.com/athombv/homey/issues/2743)

**Comment by caseda** [comment]
This should be fixed in 2.0.3, if it still occurs, I'll probably receive the messages, but feel free to re-open
