### ISSUE TITLE
Add support TZ66 to the app

### ISSUE THREAD

**Issue by sjaakie33** [caseda/com.tkbhome#4]
good day.

TZ65 productTypeId not correct at app.json line 132
this has to be:
productTypeId 258 
productId 4128

**Comment by caseda** [comment]
are you sure it is the TZ65 and not the TZ66? since i have the TZ65 myself ;)

where do you see the numbers? in device's settings?

**Comment by sjaakie33** [comment]
Sorry my mistake

I have the T66-S and D



[cid:image001.png@01D24CD6.0CD58D80]


Van: R Mengers [mailto:notifications@github.com]
Verzonden: vrijdag 2 december 2016 17:43
Aan: caseda/com.tkbhome <com.tkbhome@noreply.github.com>
CC: sjaakie33 <sjaakie33@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [caseda/com.tkbhome] TZ65 productTypeId not correct at app.json (#4)


are you sure it is the TZ65? since i have the TZ65 myself ;)

where do you see the numbers? in device's settings?

**Comment by caseda** [comment]
I'll add the TZ66 (S and D, since they are the same theoretically, like the TZ65) when i have fixed the TZ65.

i don't know when though, pretty busy at the moment, sorry.
hope to get some time free next week or so.

**Comment by caseda** [comment]
seeing that you looked into the code,
can i ask you if you, if you also know how to side load the (z-wave) app to test if it works before sending it to the app store?

have added it now to the github version at least

**Comment by sjaakie33** [comment]
app crashed after included TZ66.
inclusion when ok 

output:
Stack trace:

Error: missing_settings_key: led_behaviour
at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:211:51
at Array.forEach (native)
at ZwaveDriver.settings (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:200:18)
at /homey-app/manager/drivers.js:207:21
at ZwaveDriver.drivers.(anonymous function).ready (/homey-app/manager/drivers.js:131:9)
at eventListeners.clientDriverMessage (/homey-app/manager/drivers.js:170:10)
at /homey-app/manager/drivers.js:26:41
at Object.Homey.ready (/homey-app/homey.js:1:1008)
at /homey-app/manager/drivers.js:25:11
at /homey-app/helpers/client.js:1:1077

Exit code: 1
Exit signal: null

**Comment by sjaakie33** [comment]
and also 

![image](https://cloud.githubusercontent.com/assets/20959719/21219796/825c46f6-c2b6-11e6-9b40-2ca34b6d1b41.png)

**Comment by caseda** [comment]
Hmm a setting crash of something I copy pasted since settings are the same for the 65 and 66, but thats easy fixable. 

The other one though.. Makes it look like all websites have the command class overview wrong/incomplete.

Could you supply me the node information?
It is written in Chrome 's console (tab) when you include it as a basic device (so if no app was found) 
I think I know what it is, but want to know for sure

Thanks for taking the time to debug though :smile:

**Comment by sjaakie33** [comment]
No problem.

Node info:

[cid:image001.png@01D256CF.BA056360]

Van: R Mengers [mailto:notifications@github.com]
Verzonden: donderdag 15 december 2016 11:51
Aan: caseda/com.tkbhome <com.tkbhome@noreply.github.com>
CC: sjaakie33 <sjaakie33@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [caseda/com.tkbhome] Add support TZ66 to the app (#4)


Hmm a setting crash of something I copy pasted since settings are the same for the 65 and 66, but thats easy fixable.

The other one though.. Makes it look like all websites have the command class overview wrong/incomplete.

Could you supply me the node information?
It is written in Chrome 's console (tab) when you include it as a basic device (so if no app was found)
I think I know what it is, but want to know for sure

Thanks for taking the time to debug though 😄

**Comment by caseda** [comment]
Hmm, looks like including images via email reply is not working :p only seeing the code

**Comment by sjaakie33** [comment]
Hmm retry

with app

![image](https://cloud.githubusercontent.com/assets/20959719/21223323/db59ab08-c2c6-11e6-8cba-b1ae50942436.png)

without app
![image](https://cloud.githubusercontent.com/assets/20959719/21223383/336ec166-c2c7-11e6-947a-17db02aeb481.png)

**Comment by caseda** [comment]
Yeah, that's what I thought already yesterday evening when I read that is just a normal switch and not a dimmer.

Even though that's not chrome's console (tab) but devices settings, but still got my answer

Thanks going to work on it again this evening :+1:

**Comment by caseda** [comment]
ok, i have made the adjustment.

I added the debug tag as well,
to see if they are consistent with their products,
or actually used the way a switch needs to work with binary switch command class.

So if you could at least --run (instead of --install) the app, and just switch the switch(es) a few times and post whatever is printed in the CLI, that would be awesome!

I think you will manage to --run the app, but if you can't make it work or don't see anything come in, then, i'll see if i can get my hands on the switch myself. 😄

**Comment by sjaakie33** [comment]
works correctly what i can see

debug output:
-------------------------------------------------
com.tkbhome running...
[debug] get onoff
[debug] ------------------------------------------
[debug] Node: 575197b5-f534-422d-bc1e-c56d8f4bd58e
[debug] - Battery: false
[debug] - CommandClass: COMMAND_CLASS_SWITCH_BINARY
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- SWITCH_BINARY_GET
[debug] --- SWITCH_BINARY_REPORT
[debug] --- SWITCH_BINARY_SET
[debug] - CommandClass: COMMAND_CLASS_ASSOCIATION
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- ASSOCIATION_GET
[debug] --- ASSOCIATION_GROUPINGS_GET
[debug] --- ASSOCIATION_GROUPINGS_REPORT
[debug] --- ASSOCIATION_REMOVE
[debug] --- ASSOCIATION_REPORT
[debug] --- ASSOCIATION_SET
[debug] - CommandClass: COMMAND_CLASS_SWITCH_ALL
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- SWITCH_ALL_GET
[debug] --- SWITCH_ALL_OFF
[debug] --- SWITCH_ALL_ON
[debug] --- SWITCH_ALL_REPORT
[debug] --- SWITCH_ALL_SET
[debug] - CommandClass: COMMAND_CLASS_CONFIGURATION
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- CONFIGURATION_GET
[debug] --- CONFIGURATION_REPORT
[debug] --- CONFIGURATION_SET
[debug] - CommandClass: COMMAND_CLASS_POWERLEVEL
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- POWERLEVEL_GET
[debug] --- POWERLEVEL_REPORT
[debug] --- POWERLEVEL_SET
[debug] --- POWERLEVEL_TEST_NODE_GET
[debug] --- POWERLEVEL_TEST_NODE_REPORT
[debug] --- POWERLEVEL_TEST_NODE_SET
[debug] - CommandClass: COMMAND_CLASS_VERSION
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- VERSION_COMMAND_CLASS_GET
[debug] --- VERSION_COMMAND_CLASS_REPORT
[debug] --- VERSION_GET
[debug] --- VERSION_REPORT
[debug] - CommandClass: COMMAND_CLASS_MANUFACTURER_SPECIFIC
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- MANUFACTURER_SPECIFIC_GET
[debug] --- MANUFACTURER_SPECIFIC_REPORT
[debug] - CommandClass: COMMAND_CLASS_BASIC
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- BASIC_GET
[debug] --- BASIC_REPORT
[debug] --- BASIC_SET
[debug] ------------------------------------------

[debug]  COMMAND_CLASS_SWITCH_BINARY->SWITCH_BINARY_GET args: {} cb: true
[debug]  COMMAND_CLASS_SWITCH_BINARY SWITCH_BINARY_GET args: {} err: null result: { 'Value (Raw)': <Buffer ff>, Value: 'on/enable' }
[debug] node.CommandClass['COMMAND_CLASS_SWITCH_BINARY'].on('report') arguments: { '0': { value: 3, name: 'SWITCH_BINARY_REPORT' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 'on/enable' },
  '2': null }
[debug] get onoff
[debug] set onoff false
[debug]  COMMAND_CLASS_SWITCH_BINARY
                                        ->SWITCH_BINARY_SET args: { 'Switch Value': 'off/disable' }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[debug] set onoff true
[debug]  COMMAND_CLASS_SWITCH_BINARY
                                        ->SWITCH_BINARY_SET args: { 'Switch Value': 'on/enable' }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] set onoff false
[debug]  COMMAND_CLASS_SWITCH_BINARY
                                        ->SWITCH_BINARY_SET args: { 'Switch Value': 'off/disable' }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[debug] set onoff true
[debug]  COMMAND_CLASS_SWITCH_BINARY
                                        ->SWITCH_BINARY_SET args: { 'Switch Value': 'on/enable' }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] set onoff false
[debug]  COMMAND_CLASS_SWITCH_BINARY
                                        ->SWITCH_BINARY_SET args: { 'Switch Value': 'off/disable' }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[debug] set onoff true
[debug]  COMMAND_CLASS_SWITCH_BINARY
                                        ->SWITCH_BINARY_SET args: { 'Switch Value': 'on/enable' }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] settings() newSettingsObj { led_behaviour: '1',
  led_behaviour_data: '2',
  invert_switch: '0' } oldSettingsObj { led_behaviour: '0',
  led_behaviour_data: '2',
  invert_switch: '0' } changedKeysArr [ 'led_behaviour' ]
[debug] CONFIGURATION_SET index: 3 size: 1 newValue <Buffer 01>
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 10 01 25 85 27 70 73 86 72> }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 10 01 25 85 27 70 73 86 72> }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 10 01 25 85 27 70 73 86 72> }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 10 01 25 85 27 70 73 86 72> }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 10 01 25 85 27 70 73 86 72> }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 10 01 25 85 27 70 73 86 72> }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 10 01 25 85 27 70 73 86 72> }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 10 01 25 85 27 70 73 86 72> }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 10 01 25 85 27 70 73 86 72> }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }

**Comment by caseda** [comment]
Great, those are the values I was expecting, at least the devices work the same.
Only one more change so the flow cards work as well
Then going to send it for acceptence in the app store

I thank you for your awesome help

**Comment by caseda** [comment]
support has been added in latest update, closing it now
