### ISSUE TITLE
Please add support for more Wave plus versions

### ISSUE THREAD

**Issue by WedenofSweden** [caseda/com.tkbhome#42]
Hi 

It would be great to have support for the new Wave Plus versions like TZ57 Plus and TZ56s Plus

**Comment by caseda** [comment]
If you can supply me with verified ID numbers, I can look into this. (the alliance's website is not reliable for tkb home devices, neither is open zwave and open hab)

Though no timeline can be given at all if you supply them, atleast not until athom fixes their validator.

**Comment by WedenofSweden** [comment]
Hi

Ok, thanks!
Attached are a pic of the two types[Image]

**Comment by caseda** [comment]
Email attached images do not show up on github, so if you please could upload then on github itself I would appreciate it.

**Comment by WedenofSweden** [comment]
[
![image-2](https://user-images.githubusercontent.com/45016442/48467739-1118c680-e7ea-11e8-8668-1aaed4994dc2.png)
](url)

**Comment by caseda** [comment]
These boxes don't show any Id's though, need the manufacturer ID, product id, and product type ID.
You can find them in the device settings if you include them as generic z wave devices (that happens if you include it without any apps that support it)

**Comment by WedenofSweden** [comment]
Sorry!

TZ56S Plus
Manefacturer ID 280
Product type ID 785

TZ57 Plus
Manefacturer ID 280
Product type ID 785

**Comment by caseda** [comment]
Just noticed that i'm still missing the product id's (without type in the label). Now they seem the same id's which they probably aren't.

**Comment by WedenofSweden** [comment]
Looks like the Homey 2.0 + updated apps took care of the issue. Now it’s possible to add the dimmers.

👍🏻

Med vänlig hälsning,
Fredrik

**Comment by caseda** [comment]
Then I'm curious as what device they include as (the name it has after inclusion) so I can add the device's as "supported" in the app description.
