### ISSUE TITLE
Devices no longer working after upgrade to Homey firmware V2.x.x

### ISSUE THREAD

**Issue by SynoUser-NL** [caseda/com.tkbhome#44]
After updating Homey firmware to V2.x.x the app no longer seems to be working. No device can be controlled nor is the status read from any.

Can you please fix this by updating the app to be compatible to firmware V2.xx?
Thank you!
Den

**Comment by caseda** [comment]
The same as for issue #43 and #39 I can't fix anything untill athom fixes their validator.

Though if it is already installed, the app should work just fine in homey v2, as the app is already updated with that in mind.

**Comment by SynoUser-NL** [comment]
Thanks for your quick reply!

The app was already installed when I updated to Homey V2. It worked perfectly in V1.5.x and had very few problems with it. Now I have multiple devices that are not working anymore.

By the way: in V2 app lilst, the TKBhome app displays a trailing circle where other apps are displaying a Pause icon..

Thanks for your assistance, Den

**Comment by caseda** [comment]
It can be that it is one of the homey trigger issues that are there.
Please try again after rc8

**Comment by SynoUser-NL** [comment]
Updating to RC7 seems to have fixed the issues. Thanks for your quick support!

**Comment by glennhmjoat** [comment]
im on RC9, Validator still dosnt work, do you have any ways to get around this as its a beta environment anyway

**Comment by sh1536** [comment]
Hi, may I ask why v2.02 is not in Homey APPs, because I found that v2.02 already supports TZ74, but V2.01 in Homey APPs does not support this?


Not from a country that speaks English, there may be spelling mistakes, please forgive, thanks.

**Comment by basd82** [comment]
In the public version of homey 2.0 TKB is not working
Due to multipel isues i did factory reset en now i can't install it

**Comment by tooxe** [comment]
I have the same issue as above. It worked fine before (Homey 2.0) but since I  hade tu reinstall I’m not able to install again ...

**Comment by glennhmjoat** [comment]
> I have the same issue as above. It worked fine before (Homey 2.0) but since I had to reinstall I’m not able to install again ...

> In the public version of homey 2.0 TKB is not working
> Due to multiple issues i did factory reset en now i can't install it

Log a fault / support ticket with Athom, more tickets logged the more chance it will get resolved (i hope)

**Comment by caseda** [comment]
the validator has been fixed, so nothing athom can do about it now, i just need more time (things that i don't have much of) to fix any lasting issues that are still present in the app.

**Comment by basd82** [comment]
> the validator has been fixed, so nothing athom can do about it now, i just need more time (things that i don't have much of) to fix any lasting issues that are still present in the app.

DOes it mean it now can be installed in 2.0.0

**Comment by caseda** [comment]
Fixed with 2.0.3
