### ISSUE TITLE
TZ35D right switch gone in Flow Cards

### ISSUE THREAD

**Issue by juw2** [caseda/com.tkbhome#48]
Hi.
Since the last update, 2.0.3, the only options available in the flow cards are:
Turned on
Turned off
Dim level changed

If I install version 2.0.1 (have a copy of that on my pc) I also get:
Right switched on
Right switched off
Right switched 2x on
Right switched 2x off

Br
Jonas

**Comment by juw2** [comment]
Oh, I'm on Homey firmware 2.0.0

**Comment by caseda** [comment]
woops, sorry that is my mistake, didn't pay enough attention when moving it to the new composer, will be fixed in 2.0.4 (now awaiting approval in the store)

thank you for reporting

**Comment by caseda** [comment]
The update is online, sorry for any inconvenience.

It should fix itself when you install it.

**Comment by caseda** [comment]
Fixed with 2.0.4, if they still aren't there for some reason, feel free to re-open
