### ISSUE TITLE
Wall dimmers not working after latest update

### ISSUE THREAD

**Issue by SynoUser-NL** [caseda/com.tkbhome#52]
Hi Marco,

After the latest update of the app, my wall dimmers can not be controlled by Homey anymore. The plugin modules appear to work fine. In Homey V2 (fully updated), all tkb home device tiles display a yellow dot in the upper right corner.
I've already restarted the app, but to no avail. Can you please fix the issue?

Thanks!
DenW

**Comment by caseda** [comment]
Who's Marco? :thinking:

Not sure when you updated, but the latest update (v2.0.5) is already a month old, which contains no possible way of breaking the app whatsoever.
Have you had dimmer that didn't work for a month?
The same goes for all versions past v2.0.1.

But which device are we talking about, tkb app has 14 drivers, which support over 20 different devices, and as far as I know I'm not psychic, so I will not know which device.

Also which homey version is good information, not just "the latest" I don't know if you run stable, or beta, or are even an alpha tester, or that you did wait a month to also update that.
The same for any other information, what is the distance, do they work when near homey, did you ptp homey for several minutes.

As for an app issue, not very likely as you are the first one in a month time after the update.

**Comment by SynoUser-NL** [comment]
Welgemeende excuses, Remco.. Allereerst voor je naam, daarnaast voor het
tekort aan informatie. Die was inderdaad heel ver van ook maar enigszins
volledig en\of bruikbaar voor jou.
Ik meen me te herinneren dat er afgelopen week een update is geweest van de
TKBhome app.. maar ik ben blijkbaar abuis.
Denk dat ik ernstig aan vakantie toe ben,..

Sluit het issue maar.. ik ga even zelf verder kijken wat ik kan vinden..

Nogmaals excuses!
Vriendelijke groet, Den
