### ISSUE TITLE
Add support for TZ68E

### ISSUE THREAD

**Issue by jimvlambe** [caseda/com.tkbhome#53]
I am unable to add TZ68E. Have tried adding as TZ69E and TZ68 without luck. Please add support. Iam am using Homey 2.0.4

**Comment by caseda** [comment]
Does it not include at all? Or does it include as generic zwave device (so can't find an app during inclusion)?
Please be a bit more specific.

If it is that it includes as generic zwave device, please post the ID numbers of the device that are shown in the device's settings after inclusion as generic zwave device.

**Comment by jimvlambe** [comment]
Ooops, should have added that. It will not include at all even as generic z-wave device..

**Comment by caseda** [comment]
then it is not an app issue.

did you (factory) reset the device before trying to include?

**Comment by jimvlambe** [comment]
Yes. So it seems I have a useless lump. Thanks, anyway.

**Comment by caseda** [comment]
if it did reset then it can be 2 things though, it can be the wrong frequentie, or the module is just broken.

So make sure it is the right frequency for your homey.
If it is, then it most likely is just a broken device.
