### ISSUE TITLE
Add support TZ75

### ISSUE THREAD

**Issue by bertdeelman** [caseda/com.tkbhome#56]
Hi,

Is there any chance that the TZ75 (Rollershutter Controller) will be added? 

Regards,
Bert

**Comment by caseda** [comment]
As I don't have this device, and tkb is known to be weird with their devices, I will not be adding them, someone else will have to do it.

**Comment by bertdeelman** [comment]
Hi,

Ok fair answer. Thanks. 

Regards,
Bert
