### ISSUE TITLE
TKB Home TZ69 No Icon on Device-Card

### ISSUE THREAD

**Issue by CyberSponk** [caseda/com.tkbhome#61]
Homey 3.1.0
Tkb-App 2.0.5

After adding the Device to Homey no Device-Icon is shown on the Device-Card.

**Comment by caseda** [comment]
I've fixed the icons in 2.0.6.
You can find the 2.0.6 update in the test part of the appstore:
https://homey.app/a/com.tkbhome/test/
And please confirm that your issue was fixed in this update.
