### ISSUE TITLE
Add invert output feature on TZ74 ?

### ISSUE THREAD

**Issue by PaulSchryve** [caseda/com.tkbhome#64]
Hello

Could you please add an "invert output" parameter ?

Some Qubino switches propose this feature, allow to invert on / off output on the switches.

Usefull for example in France, for heaters, as we use switches with a diod to send an ON signal (Heater "Confort" mode" = No signal = TZ74 OFF), and a half 220v / 50 hz signal for the OFF signal (heater "Hors gel" signal = TZ74 ON).

So this feature will be usefull for all French people managing heaters with this solution.

I had a picture of the Qubino switch example.

a French documentation about 'fil pilote' that you can translate with google 
https://www.domotique-store.fr/fr/domotique/modules-domotiques/thermostats/accessoires/289-diode-de-redressement-pour-fil-pilote-1000v-1a.html

![Capture d’écran   2020-02-10 à 15 21 09](https://user-images.githubusercontent.com/51374952/74157934-76d84600-4c19-11ea-8718-b7054fb2f76d.png)

**Comment by caseda** [comment]
Qubino does this on a hardware level, tkb does not offer this option.

**Comment by PaulSchryve** [comment]
ok thanks for your answer.
