### ISSUE TITLE
TZ56 - Single & Double Wall Switch doesnt report status back Homey

### ISSUE THREAD

**Issue by Majjjo** [caseda/com.tkbhome#71]
Hi there. I read the discussion and did not find an answer whether TZ56 - Single & Double Wall Switch report back the current status to Homey. I can manage on/off from Homey but If I do it from TKB Switch I don't see change in Homey. Thanks for support.
Majjjo

**Comment by caseda** [comment]
thank you for your message.

i'm not sure TKB has _any_ devices that report by themselves, the device i had i needed to poll the current state (which is a advanced setting), and was not send by the device itself.

But TKB doesn't really follow the z-wave rules, so who know what it will/can do, it can differ for each device, even the same device, but have completely different behaviour.
Which is the reason why I stopped actively supporting this app.

**Comment by Majjjo** [comment]
Thank you for your answer and  time.Cheers. Marian sent from Y!On 27 May 2021 21:13, R Mengers ***@***.***> wrote:
thank you for your message.
i'm not sure TKB has any devices that report by themselves, the device i had i needed to poll the current state (which is a advanced setting), and was not send by the device itself.
But TKB doesn't really follow the z-wave rules, so who know what it will/can do, it can differ for each device, even the same device, but have completely different behaviour.
Which is the reason why I stopped actively supporting this app.
